### ISSUE TITLE
Multi-client realtime telemetry synchronization

### ISSUE THREAD

**Issue by univhack** [dsuryd/dotnetify-react-demo-vs2017#7] opened 2018-01-21 17:35 UTC
Hi Dicky,

DotNetify looks like a very promising framework I am really excited to dive deeper into it and learn the details of it's capabilities :)

There is a major publicly traded company that I am doing consulting work for that I think DotNetify might potentially be a great fit for. This company has a custom application that renders different perspectives of a massive stream of telemetry data in multiple widgets across multiple clients. They developed this application 10 years ago using WPF and they are very interested in rewriting it as a web app.

Sorry for the long explanation but I thought some context might help make my question more clear. I saw your real-time examples. I was particularly interested in the dashboard demo and in the LiveChart one (http://dotnetify.net/index/LiveChart)   

My two main questions are: 
-   How would you recommend to go about having real time telemetry data be delivered at almost the same time (synchronized) across multiple clients (in DotNetify)?

- Are there any particular considerations that I need to take into account if I also need near real-time synchronization between the different "widgets" (within each client) that show different perspectives of related telemetry?

The telemetry data in question is about many aspects of the electrical grid (distribution, generation, consumption, health status, etc) so the operators need to be able to see data near real-time both within the different widgets in their screen and also all operators should be seeing the same data (not 100% real-time but as close to that as possible).

Thanks for your help and for putting this really cool framework together!

**Comment by dsuryd** [comment] 2018-01-22 03:03
Thank you for the encouraging feedback :)
Here's an architecture I'd recommend:

![image](https://user-images.githubusercontent.com/14990482/35203035-e82fd036-feda-11e7-925d-f47285136e40.png)

The Subcription Service is both a consumer to the Message Broker, and a producer for the Transformer services (services that provide different perspectives of the data).  On the presentation layer, the simplest approach is to keep one view model to relay data to various widgets, similar to the dotNetify-React SPA template's dashboard demo.

**Comment by univhack** [comment] 2018-01-22 03:21
Thanks a lot for your quick and detailed reply!  That would definitely help keep the widgets in each individual client in sync by sharing the same view model. 

How would you recommend to go about maintaining the clients in sync (having them show the same data in near real-time)?. For example, is there a concept in DotNetify equivalent to having all the clients subscribe to a hub or to a topic and all receive the data at the same time?

Thanks!
Freddy

**Comment by dsuryd** [comment] 2018-01-22 03:44
IMHO, the responsibility of getting multiple clients in sync should not be on the presentation layer where dotNetify operates, but on the service object that provides the data.  I would place that responsibility on the Subscription Service, which may run as a singleton for all those clients in that same web server.

**Comment by univhack** [comment] 2018-01-22 04:07
From the MVVM architecture point of view you are right. I was just hoping that there might be a way to leverage SignalR Core's Hubs capabilities to have clients subscribe to a specific Hub and then get the data from there (or to be able to define something akin to a Topic for the same purpose)

I saw your example about the Bunny Rabbit where the Pen.cs is a singleton service. Would you recommend using something like that or is there a way to leverage Hubs subscriptions somehow. I know that the architecture that you are using on top of SignalR is different from the original one but I am curious to see if you had any ideas to be able to populate the view models based on the Hub that their View is "subscribed" to.

**Comment by dsuryd** [comment] 2018-02-28 02:39
Closing this; the issue is tracked in the dotNetify github.

**Closed by dsuryd** 2018-02-28 02:39 UTC
